### ISSUE TITLE
Unable to use external profile

### ISSUE THREAD

**Issue by italy-portugal** [AtomLinter/atom-linter-perlcritic#17]
After updating to 1.1.0, I started receiving the following error:
```
Error: Unknown option: p ~/Projects/settings/perlcriticrc
Usage:
      perlcritic [-12345 | --brutal | --cruel | --harsh | --stern | --gentle]
                 [--severity number | name] [{-p | --profile} file | --noprofile]
                 [--top [ number ]] [--theme expression] [--include pattern]
                 [--exclude pattern] [{-s | --single-policy} pattern]
                 [--only | --noonly] [--profile-strictness {warn|fatal|quiet}]
                 [--force | --noforce] [--statistics] [--statistics-only]
                 [--count | -C] [--verbose {number | format}] [--allow-unsafe]
                 [--color | --nocolor] [--pager pager] [--quiet]
                 [--color-severity-highest color_specification]
                 [--color-severity-high color_specification]
                 [--color-severity-medium color_specification]
                 [--color-severity-low color_specification]
                 [--color-severity-lowest color_specification]
                 [--files-with-violations | -l]
                 [--files-without-violations | -L]
                 [--program-extensions file_name_extension]
                 {FILE | DIRECTORY | STDIN}
      perlcritic --profile-proto
      perlcritic { --list | --list-enabled | --list-themes | --doc pattern [...] }
      perlcritic { --help | --options | --man | --version }
    at ChildProcess.<anonymous> (/Users/italy-portugal/.atom/packages/linter-perlcritic/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
I have the Additional Commandline options set to: `-p ~/Projects/settings/perlcriticrc`

If I set it to `--profile ~/Projects/settings/perlcriticrc`, the first line of the error changes to:

```
Error: Unknown option: profile ~/Projects/settings/perlcriticrc
```

I am on Mac OSX Yosemite running Atom 1.9.8

**Comment by whity** [comment]
hi @italy-portugal , please update, it should be fixed now.

**Comment by italy-portugal** [comment]
Great! I managed to get the plugin functioning after working around some problems: 

1. the regex matched dashes in the middle. (modifying it to be `/\-\-?\w+[\s=]+?/` worked.)
2. The `~` symbol was not expanding correctly, so that I was receiving a "could not find file" error. (expanding the setting to use the full file-path worked).

Thanks!

**Comment by whity** [comment]
hi, I didn't quite understood the first issue, can you be more explicit.
